TohidContacts/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TohidContacts.Data;
using TohidContacts.Models;
using TohidContacts.ModelViews;

namespace TohidContacts.Controllers
{

    public class ContactsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHostingEnvironment _hostingEnv;


        public ContactsController(ApplicationDbContext db, IHostingEnvironment hostingEnv)
        {
            _db = db;
            _hostingEnv = hostingEnv;
        }
        public IActionResult NewContact()
        {
            NewContactModelView newContactModelView = new();
            newContactModelView.contact = new();
            newContactModelView.categories = _db.Categories.ToList();

            return View(newContactModelView);
        }

        // Get Edit
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var obj = _db.Contacts.Include(contact => contact.Phones).FirstOrDefault(c => c.Id == id);

            if (obj == null)
            {
                return NotFound();
            }

            NewContactModelView contactModelView = new();
            contactModelView.categories = _db.Categories.ToList();
            contactModelView.contact = obj;
            contactModelView.editMode = true;

            return View(contactModelView);
        }


        // Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NewContactModelView obj)
        {

           
            var phones = _db.Phones.Where(phone => phone.ContactId == obj.contact.Id);
            _db.Phones.RemoveRange(phones);
            _db.SaveChanges();


            if (obj.ContactImageFile != null)
            {
                string uniqueFileName = UploadedFile(obj.ContactImageFile);
                obj.contact.Image = uniqueFileName;
            }

            _db.Contacts.Update(obj.contact);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(NewContactModelView obj)
        {
           
            if (obj.ContactImageFile != null)
            {
                string uniqueFileName = UploadedFile(obj.ContactImageFile);
                obj.contact.Image = uniqueFileName;
            }

            _db.Contacts.Add(obj.contact);
            _db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        private string UploadedFile(IFormFile ProfileImage)
        {
            string uniqueFileName = null;

            if (ProfileImage != null)
            {
                string uploadsFolder = Path.Combine(_hostingEnv.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + ProfileImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    ProfileImage.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        public IActionResult Details(int id)
        {
            Contact contact = _db.Contacts.Include(contact => contact.Phones).Include(contact => contact.Category).FirstOrDefault(c => c.Id == id);
            return View(contact);
        }


        public IActionResult Delete(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var obj = _db.Contacts.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Contacts.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index", "Home");

        }

    }
}

TohidContacts/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TohidContacts.Data;
using TohidContacts.Models;
using TohidContacts.ModelViews;

namespace TohidContacts.Controllers
{
    public class SettingsController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SettingsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
           
            //get categories from db
            List<Category> categories = _db.Categories.ToList();
            SettingsViewModel settingsViewModel = new();
            settingsViewModel.categories = categories;

            return View(settingsViewModel);
        }
    }
}

TohidContacts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TohidContacts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script>
        var darkMode = localStorage.getItem("darkMode");
        console.log("daaark", darkMode);
        if (darkMode == 1) {
            console.log("daaark");

            var oldlink = document.getElementsByTagName("link").item(1);

            var newlink = document.createElement("link");
            newlink.setAttribute("rel", "stylesheet");
            newlink.setAttribute("type", "text/css");
            newlink.setAttribute("href", 'css/site-dark.css');
            console.log("old", oldlink);
            console.log("new", newlink);

            document.getElementsByTagName("head").item(0).replaceChild(newlink, oldlink);

        }
    </script>
</head>
<body>
    
    <div class="h-100 dis-scroll">
        <div class="side-nav w-25 d-none d-md-flex flex-column text-center border-left border-light">
            <div class="h-15 text-center">
                <img src="~/images/logo.png" class="logo" alt="logo" />
            </div>
            <div class="h-85 d-rtl px-2 text-muted">
                <div class="w-75 mx-auto">
                    <a class="d-flex align-items-center mt-5" asp-controller="Home" asp-action="Index">
                        <span class="w-25 material-icons md-18 ml-2">home</span>
                        <small class="font-weight-bold">صفحه اصلی</small>
                    </a>
                    <a class="d-flex align-items-center mt-3" asp-controller="Home" asp-action="Index" asp-route-IsFav="true">
                        <span class="w-25 material-icons md-18 ml-2">favorite</span>
                        <small class="font-weight-bold">مخاطبان محبوب</small>
                    </a>
                    <a class="d-flex align-items-center mt-3" asp-controller="Contacts" asp-action="NewContact">
                        <span class="w-25 material-icons md-18 ml-2">person_add</span>
                        <small class="font-weight-bold">تعریف مخاطب جدید</small>
                    </a>

                    <a class="d-flex align-items-center mt-3" asp-controller="Settings" asp-action="Index">
                        <span class="w-25 material-icons md-18 ml-2">settings</span>
                        <small class="font-weight-bold">تنظیمات</small>
                    </a>
                    <a  class="d-flex align-items-center mt-3" asp-controller="Home" asp-action="About">
                        <span class="w-25 material-icons md-18 ml-2">info</span>
                        <small class="font-weight-bold">درباره نرم افزار</small>
                    </a>
                </div>
                
            </div>
            <img src="~/images/vh.svg" class="bg-vh" />

        </div>
        <div class="bottom-nav d-md-none d-flex my-card">
            <a  asp-controller="Home" asp-action="About" class="bottom-tab border-right"><span class="material-icons icon-sm mt-2" >info</span><small>اطلاعات</small>  </a>
            <a asp-controller="Settings" asp-action="Index" class="bottom-tab border-right"><span class="material-icons icon-sm mt-2">settings</span><small>تنظیمات</small></a>
            <a asp-controller="Contacts" asp-action="NewContact" class="bottom-tab border-right"><span class="material-icons icon-sm mt-2">add_circle</span><small>ایجاد</small></a>
            <a asp-controller="Home" asp-action="Index" asp-route-IsFav="true" class="bottom-tab border-right"><span class="material-icons icon-sm mt-2">favorite</span><small>علاقمندی</small></a>
            <a asp-controller="Home" asp-action="Index" class="bottom-tab"><span class="material-icons icon-sm mt-2">home</span><small>خانه</small></a>
        </div>
        <main role="main" class="position-relative col col-md-9">
            @RenderBody()
        </main>
        <img src="~/images/trees.svg" class="bg-trees"/>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert2.all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>