TohidContacts/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TohidContacts.Data;
using TohidContacts.Models;

namespace TohidContacts.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;


        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        // Get Create
        public IActionResult Create()
        {
            return View();
        }

        // Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }
            _db.Categories.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index", "Settings");
            
        }

        // Get Edit
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var obj = _db.Categories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }
            _db.Categories.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index", "Settings");

        }

        public IActionResult Delete(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var obj = _db.Categories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Categories.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index", "Settings");

        }
    }
}

TohidContacts/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TohidContacts.Data;
using TohidContacts.Models;
using TohidContacts.ModelViews;

namespace TohidContacts.Controllers
{
    public class SettingsController : Controller
    {
        private readonly ApplicationDbContext _db;
        public SettingsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
           
            //get categories from db
            List<Category> categories = _db.Categories.ToList();
            SettingsViewModel settingsViewModel = new();
            settingsViewModel.categories = categories;

            return View(settingsViewModel);
        }
    }
}

TohidContacts/Views/Settings/index.cshtml
@{
    ViewData["Title"] = "Settings";
}
@model TohidContacts.ModelViews.SettingsViewModel

<div class="py-5 px-3">
    <h5 class="text-muted my-4">تنظیمات</h5>
    <div class="row pt-3">
        <div class="col-12 col-md-6">
            <p class="m-0 px-2"><small><strong>دسته بندی مخاطب ها</strong></small></p>
            <div>
                @if (Model.categories.Count() > 0)
                {
                    @foreach (var category in Model.categories)
                    {
                        <div class="my-card mt-2 align-items-center row mx-0 p-2">
                            <span class="col"><strong>@category.Name</strong></span>
                            <div class="col-auto color-tag rounded text-white mr-2" style="background:@category.Label">&nbsp;</div>
                            <a asp-controller="Category" asp-action="Edit" asp-route-Id="@category.Id" class="col-auto material-icons md-18 text-info mr-2">edit</a>
                            <span class="col-auto material-icons md-18 text-danger pointer"
                                  onclick="Swal.fire({
                                  html: 'آیا برای حذف دسته بندی @category.Name اطمینان دارید؟' ,
                                  showCancelButton: true,
                                  cancelButtonText:`انصراف`,
                                  confirmButtonText: `حذف`,
                                  confirmButtonColor:'#d33',
                                  icon:'warning',
                                  }).then((result)=>
                                {
                                if (result.isConfirmed) {
                                window.location.href = 'Category/Delete/@category.Id'
                                }
                                })">delete_forever
                            </span>







                        </div>
                    }
                }
                else
                {
                    <p>هیچ دسته بندی تعریف نکرده اید!</p>
                }
            </div>
            <a asp-controller="Category" asp-action="Create" class="w-100 t-color d-rtl d-flex align-items-center justify-content-center p-4">
                <span class="material-icons md-18 mx-2">add_circle</span>
                <span><strong>افزودن دسته بندی جدید</strong></span>
            </a>
            <div class="t-button">ثبت</div>
        </div>
        <div class="col-12 col-md-6">
            <p class="m-0 mt-4 mt-md-0 px-2"><small><strong>تنظیمات ظاهری</strong></small></p>
            <div class="my-card mt-2 align-items-center row mx-0 p-2" onclick="changeCSS()">
                <span class="col"><strong>دارک مود</strong></span>
                <span class="material-icons icon-sm">
                    nightlight_round
                </span>
            </div>
        </div>
    </div>


@section Scripts{
    <script type="text/javascript">

        function changeCSS() {
            var darkMode = localStorage.getItem('darkMode');

            if (darkMode == null) {
                darkMode = 0;
            }
            console.log(darkMode);
            var oldlink = document.getElementsByTagName("link").item(1);

            var newlink = document.createElement("link");
            newlink.setAttribute("rel", "stylesheet");
            newlink.setAttribute("type", "text/css");
            newlink.setAttribute("href", (darkMode == 0 ? 'css/site-dark.css' : 'css/site.css'));
            console.log("old", oldlink);
            console.log("new", newlink);

            document.getElementsByTagName("head").item(0).replaceChild(newlink, oldlink);

            var newStatus = (darkMode == 1 ? 0 : 1);
            if (darkMode == 1) {
                newStatus = 0;
            } else {
                newStatus = 1;
            }
            console.log("newww", newStatus);
            localStorage.setItem('darkMode',newStatus);
        }

    </script>
}